services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: uptime_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./uptime.db
      - SECRET_KEY=SUPER_SECRET_JWT_KEY_FOR_UPTIME_CHECKER_APP_2026_SECURE_TOKEN
    volumes:
      - backend_data:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: uptime_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  backend_data:
